### ISSUE TITLE
question about generating lidar image

### ISSUE THREAD

**Issue by harborsarah** [timbroed/HRFuser#2]
Hello,

I would like to ask, in the function _fill_trainval_infos(), when you generate the lidar image, I found out that you give these two parameters:
lidar_scale_factor=100 and shift=200
Also, the background of the lidar image is 20000. Are there any reasons for using these huge numbers stored in the image?
I am sorry I am not so familiar with Lidar, so I would like to ask how you came up with these scale and shift things.

Thanks a lot for your answer!

**Comment by timbroed** [comment]
Hello,

This is done to store the projections as uint16 PNG images as they can then be easily handled when loading similarly to the camera inputs. 

These factors are used in order to save the projections as PNG files with uint16 in each pixel. Since this format does not allow negative values we shifted every value by 200 (shift) and multiply them by 100 (lidar_scale_factor) in order to keep a high accuracy in the measurements.

These values worked well for us, but you could set other values as these are stored in the dict ``info['lidar_img']``, automatically loaded and reverted [here](https://github.com/timbroed/HRFuser/blob/0c3c0464198728e0230b827e3ff10fd0f618182e/mmdet/datasets/pipelines/loading.py#L309). So we have our normal image with the background set to 0 after loading the image with ``LoadProjectedSensorImageFile``.

Hope this helps.

**Comment by harborsarah** [comment]
> Hello,
> 
> This is done to store the projections as uint16 PNG images as they can then be easily handled when loading similarly to the camera inputs.
> 
> These factors are used in order to save the projections as PNG files with uint16 in each pixel. Since this format does not allow negative values we shifted every value by 200 (shift) and multiply them by 100 (lidar_scale_factor) in order to keep a high accuracy in the measurements.
> 
> These values worked well for us, but you could set other values as these are stored in the dict `info['lidar_img']`, automatically loaded and reverted [here](https://github.com/timbroed/HRFuser/blob/0c3c0464198728e0230b827e3ff10fd0f618182e/mmdet/datasets/pipelines/loading.py#L309). So we have our normal image with the background set to 0 after loading the image with `LoadProjectedSensorImageFile`.
> 
> Hope this helps.

Thanks a lot for your quick reply.
This helps a lot! I will go through it in more detail.
